services:
  app1:
    build:
      context: ./Client_1
      dockerfile: Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_IP=nats
    networks:
      - my-network

  app2:
    build:
      context: ./Client_2
      dockerfile: Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_IP=nats
    networks:
      - my-network

  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - my-network

networks:
  my-network:
